// Generated by CoffeeScript 2.7.0
import React from 'react';

import ReactDOM from 'react-dom/client';

import App from './App';

ReactDOM.createRoot(document.getElementById('root')).render(React.createElement(App));
