// Generated by CoffeeScript 2.7.0
var get_table_data;

import _ from 'lodash';

import h from 'react-hyperscript';

import '../../src/css/sticky_table.css';

export var Table = function({header, data}) {
  // h 'div', [
  return h('.sticky-table', [
    h('table.zebra-table.border-table',
    [
      // h 'table.zebra-table.round-table', [
      h('thead',
      [
        h('tr',
        header.map(function(head) {
          return h('th',
        head);
        }))
      ]),
      h('tbody',
      data.map(function(row,
      row_i) {
        return h('tr',
      row.map(function(col,
      col_i) {
          return h('td',
      col);
        }));
      }))
    ])
  ]);
};

export var DivTable = function({header, data}) {
  return h('div', [
    h('.div-table',
    [header].concat(data).map(function(row,
    row_i) {
      return h('.div-tr',
    row.map(function(col,
    col_i) {
        return h('.div-td',
    col);
      }));
    }))
  ]);
};

get_table_data = function() {
  var col_len, data, header, row_len;
  row_len = 100;
  col_len = 25;
  data = _.range(row_len).map(function(row_i) {
    return _.range(col_len).map(function(col_i) {
      return `r${row_i}_c${col_i}`;
    });
  });
  header = _.range(data[0].length).map(function(head) {
    return `h${head}`;
  });
  return {header, data};
};

export var TestTable = function() {
  var data, header;
  ({header, data} = get_table_data());
  return h(Table, {header, data});
};

export var TestDivTable = function() {
  var data, header;
  ({header, data} = get_table_data());
  return h(DivTable, {header, data});
};
