// Generated by CoffeeScript 2.7.0
var App, TestTable;

import _ from 'lodash';

import {
  useState
} from 'react';

import h from 'react-hyperscript';

import '../../css/sticky_table.css';

TestTable = function({caption, header, data}) {
  return h('.sticky-table', [
    h('table.zebra-table.round-table',
    [
      h('caption',
      caption),
      h('thead',
      [
        h('tr',
        header.map(function(head) {
          return h('th',
        head);
        }))
      ]),
      h('tbody',
      data.map(function(row,
      row_i) {
        return h('tr',
      row.map(function(col,
      col_i) {
          return h('td',
      col);
        }));
      }))
    ])
  ]);
};

App = function() {
  var caption, col_len, data, header, row_len;
  caption = 'Test Table';
  row_len = 100;
  col_len = 25;
  data = _.range(row_len).map(function(row_i) {
    return _.range(col_len).map(function(col_i) {
      return `r${row_i}_c${col_i}`;
    });
  });
  header = _.range(data[0].length).map(function(head) {
    return `h${head}`;
  });
  return h('div', [h(TestTable, {caption, data, header})]);
};

export default App;
