// Generated by CoffeeScript 2.7.0
var App, NavApp, TestTable, get_table_data;

import _ from 'lodash';

import {
  useState
} from 'react';

import h from 'react-hyperscript';

import '../../css/sticky_table.css';

import {
  NavBar,
  NavList
} from './navbar';

TestTable = function({header, data}) {
  return h('.sticky-table', [
    h('table.zebra-table.round-table',
    [
      h('thead',
      [
        h('tr',
        header.map(function(head) {
          return h('th',
        head);
        }))
      ]),
      h('tbody',
      data.map(function(row,
      row_i) {
        return h('tr',
      row.map(function(col,
      col_i) {
          return h('td',
      col);
        }));
      }))
    ])
  ]);
};

NavApp = function() {
  return h(NavBar, {
    title: 'Sticky-Table',
    collapse_items: [
      h(NavList,
      {
        nav_list: [
          {
            name: 'Menu',
            component: ''
          }
        ],
        default_index: 0,
        select_nav: function() {}
      })
    ]
  });
};

get_table_data = function() {
  var col_len, data, header, row_len;
  row_len = 100;
  col_len = 25;
  data = _.range(row_len).map(function(row_i) {
    return _.range(col_len).map(function(col_i) {
      return `r${row_i}_c${col_i}`;
    });
  });
  header = _.range(data[0].length).map(function(head) {
    return `h${head}`;
  });
  return {header, data};
};

App = function() {
  var data, header;
  ({header, data} = get_table_data());
  return h('.container-fluid', {
    style: {
      padding: 0
    }
  }, [h(NavApp), h(TestTable, {data, header})]);
};

export default App;
